### ISSUE TITLE
Discussion - Version numbers

### ISSUE THREAD

**Issue by aaronwmorris** [indilib/pyindi-client#19]
With #15 the version for pyindi-client needs to be incremented again and the version updated in the pypi.org index.

I think geehalel had intended to increment pyindi-client to 0.3 once compatibility with indi 1.9.x was completed which I think is basically the case now.

Just to throw a wild idea out there.... maybe we should increment the version to 1.9.x to kind of stay in lockstep with the indi project?

**Comment by knro** [comment]
I agree that it should probably match INDI minor version at least i.e. 1.9

**Comment by abecadel** [comment]
That's a good idea, I'll bump & release a new version

**Comment by abecadel** [comment]
done
