### ISSUE TITLE
'BaseClient' object has no attribute 'newText'  and  RecursionError: maximum recursion depth exceeded 

### ISSUE THREAD

**Issue by Akinetopsia1** [indilib/pyindi-client#41]
None of the examples work on Raspberry Pi with Raspbian GNU/Linux 10 (buster), Kernel: Linux 5.10.103-v7l+, Python 3.7.3, INDI Library: 1.9.7 / Code v1.9.7. Protocol 1.7.

**testindiclient.py** starts listing props an then fails with: 

```
2023-08-25 23:46:08,453 new property TELESCOPE_TIMED_GUIDE_NS as INDI_NUMBER for device Telescope Simulator
2023-08-25 23:46:08,454 new property TELESCOPE_TIMED_GUIDE_WE as INDI_NUMBER for device Telescope Simulator
2023-08-25 23:46:08,454 new property GUIDE_RATE as INDI_NUMBER for device Telescope Simulator
Traceback (most recent call last):
  File "/home/astroberry/.local/lib/python3.7/site-packages/PyIndi.py", line 1093, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, BaseClient, name)
  File "/home/astroberry/.local/lib/python3.7/site-packages/PyIndi.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'BaseClient' object has no attribute 'newText'
```

**vega.py** and even **tuto-minimal.py** give :

```
INDI::BaseClient::connectServer: creating new connection...
INDI::BaseClient::connectServer: Already connected.
RecursionError: maximum recursion depth exceeded
```

**tuto-monitor.py** gives:

```
INDI::BaseClient::connectServer: creating new connection...
INDI::BaseClient::connectServer: Already connected.
New device  Telescope Simulator
Traceback (most recent call last):
  File "indy-monitor.py", line 20, in newProperty
    cmonitor = PyIndi.PropertySwitch(p)
  File "/home/astroberry/.local/lib/python3.7/site-packages/PyIndi.py", line 3129, in __init__
RecursionError: maximum recursion depth exceeded
```

**Comment by knro** [comment]
Most likely because you don't have INDI v2.0.0+ on there?

**Comment by Akinetopsia1** [comment]
hmm, i would've expected an unmet requirements check and warning while installing if it's that version-specific. (it did warn about swig on my first attempt)

I'm using the astroberry distro and it's a bit behind. INDI 1.9.7 is the latest version for it i think. I messed with my install in the past in an attempt to add support for Canon .CR3 raw files but upgrading is a bit of a can of worms as i had to recompile K-Stars/Ekos, had a bunch of instabilities and i would've had to also compile QT5 IIRC -- which is a really bad idea on a pi to say the least so i eventually just reflashed a backup image. 

I'm going to leave it at that and check if i can find a previous commit that works, otherwise i guess i'll work around using indi_getprop / indi_setprop

Thx for the tip


Edit: commit [ffd939bebabdb5423cd1666f84288eafcb0996ff](https://github.com/indilib/pyindi-client/tree/ffd939bebabdb5423cd1666f84288eafcb0996ff) on Oct 12, 2022 works for me

Again, thanks for pointing me in the right direction.
